apiVersion: apps/v1
kind: Deployment
metadata:
  name: rti-clouddiscoveryservice
spec:
  selector:
    matchLabels:
      run: rti-clouddiscoveryservice
  replicas: 1
  template:
    metadata:
      labels:
        run: rti-clouddiscoveryservice
    spec:
      containers:
      - name: rti-clouddiscoveryservice
        image: kyoungho/rti-clouddiscoveryservice
        volumeMounts:
          - name: license-volume
            mountPath: /app/license
        ports:
        - containerPort: 7400
          protocol: UDP
        env:
        - name: ARGS
          value: "-verbosity 6"
      volumes:
        - name: license-volume
          configMap:
            name: rti-license
      nodeSelector:
        discovery: cds

---
apiVersion: v1
kind: Service
metadata:
  name: rti-clouddiscoveryservice
  labels:
    run: rti-clouddiscoveryservice
spec:
  ports:
  - port: 7400
    protocol: UDP
  selector:
    run: rti-clouddiscoveryservice
